module.exports = `
  type Post {
    _id: String
    title: String
    content: String
    image: String
    user: User!
  }

  type User {
    _id: String
    name: String
    email: String!
    jwt: String
    posts: [Post]!
  }

  type Query {
    allPosts: [Post]
    allUsers: [User]
  }

  type Mutation {
    addPost(
      title: String! 
      content: String!
      image: String!
    ):Post
    deletePost(
      _id: String!
    ):Post
    login(
      email: String!
      password: String!
    ):User
    register(
      name: String!
      email: String!
      password: String!
    ):User
  }
`


