module.exports = `
  type Post {
    _id: String
    title: String
    content: String
    image: String
    user: User!
    comments: [Comment]
  }

  type Comment {
    _id: String
    message: String
    post: Post
    createdAt: Date
    user: User!
  }

  type User {
    _id: String
    name: String
    email: String!
    jwt: String
    posts: [Post]!
    comments: [Comment]!
  }

  type Query {
    allPosts: [Post]
    post(_id:String!):Post
    allUsers: [User]
  }

  type Mutation {
    addPost(
      title: String! 
      content: String!
      image: String!
    ):Post
    addComment(
      post: String!
      message: String!
    ):Comment
    deletePost(
      _id: String!
    ):Post
    login(
      email: String!
      password: String!
    ):User
    register(
      name: String!
      email: String!
      password: String!
    ):User
  }

  scalar Date
`


